#!/bin/bash
set -euo pipefail

BADGE_TITLE_CHARACTERS=$(echo -n "$2" | wc -c)
BADGE_WIDTH_L=$((30 + BADGE_TITLE_CHARACTERS * 7))
BADGE_WIDTH_R='60'

if [[ "$3" == 'passing' ]]; then
    BADGE_STATUS_FG='#000000'
else
    BADGE_STATUS_FG='#000000'
fi

sed \
    -e "s#__BADGE_TITLE__#${2}#g" \
    -e "s/__BADGE_WIDTH_L__/${BADGE_WIDTH_L}/g" \
    -e "s/__BADGE_WIDTH_R__/${BADGE_WIDTH_R}/g" \
    -e "s/__BADGE_WIDTH_TOTAL__/$((BADGE_WIDTH_L + BADGE_WIDTH_R))/g" \
    -e "s/__BADGE_STATUS__/${3}/g" \
    -e "s/__BADGE_STATUS_FG__/${BADGE_STATUS_FG}/g" \
    "$1" > badge.svg
